//This is a temporary file generated by spyglass Lib2V utility from the library
//<sram_4096x8.lib>. Do not modify this or use this.
//spyglass xref filename </home/raid7_2/user12/r2921a01/hw/hw3/1121_hw3/01_RTL/./spyglass-1/core/Design_Read/spyglass_spysch/spyglass/sram_4096x8_slow_syn_0.v>
//spyglass xref version SpyGlass_vT-2022.06

//spyglass xref lineno 214, -1
`celldefine
module sram_4096x8 (Q, A, D, CLK, CEN, WEN);
    output [7:0]Q;
    input  [11:0]A;
    input  [7:0]D;
    input  CLK;
    input  CEN;
    input  WEN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine
